# .bash_profile

# Get the aliases and functions
#if [ -f ~/.bashrc ]; then
#	. ~/.bashrc
#fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

# For the lulz
alias please='sudo'

# Enhancing ls to prefix with git branch info 
# when working in a source-controlled path
alias ls='git status 2>/dev/null|grep branch;ls'

# Lazy shortcuts 
alias gitst='git status'
alias gist='git status'

# TMUS-specific stuff
if [ -f ~/.bash_tmus ]; then
	. ~/.bash_tmus
fi

# Deploy a release candidate to the [test|prod] branch
alias deploy-test='git checkout deploy-test; git merge master; git push; git checkout master'
alias deploy-prod='git checkout deploy-prod; git merge master; git push; git checkout master'

# Add the Xerces install path/variables
export PATH="$PATH:/home/ccox37/bin/xerces-c-3.1.1-x86_64-linux-gcc-3.4/bin"
export LD_LIBRARY_PATH=/home/ccox37/bin/xerces-c-3.1.1-x86_64-linux-gcc-3.4/lib:$LD_LIBRARY_PATH

