# .bash_profile

# Get the aliases and functions
#if [ -f ~/.bashrc ]; then
#	. ~/.bashrc
#fi

# For the lulz
alias please='sudo'

# Enhancing ls to prefix with git branch info 
# when working in a source-controlled path
alias ls='git status 2>/dev/null|grep branch;ls'

# Lazy shortcuts 
alias gitst='git status'
alias gist='git status'

# Log in to my home server.
alias go_home='ssh chris@klaital.com'
alias home='ssh chris@klaital.com'
alias go_aforge='ssh afsmith@abandonedforge.com'
alias go_vita='ssh vitasa@vitasa.abandonedfactory.net'

# Deploy a release candidate to the [test|prod] branch
alias deploy-test='git checkout deploy-test; git merge master; git push; git checkout master'
alias deploy-prod='git checkout deploy-prod; git merge master; git push; git checkout master'


